---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
#  - package-ecosystem: "gomod"
#    directory: "/contrib/config/apollo"
#    schedule:
#      interval: "weekly"
