blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://code-policeman.dev/en/docs/
    about: For documentation issues, open a pull request at the code-policeman/code-policeman.dev repository
